import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Title } from "./components/Title";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " m-1 mb-0 md:m-4 md:mb-0 lg:m-6 lg:mb-0"}>
        <Title />
        {children}
        <div id='footer' className='footer text-center text-slate-500 mb-2'>
          <a rel='noopener' href='https://🔗.to/simon' target="_blank">Simon Marcus</a> | 
          <a rel='noopener' href='https://github.com/simon-marcus/animal-detection-test' target="_blank"> GitHub</a> |
          <a rel='noopener' > About</a>
        </div>
      </body>
    </html>
  );
}
